# -*- coding: utf-8 -*-
"""multi_agent_research_assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ArX03d021bz0LL32Wu-FM0OptjyT6oz
"""

import os

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    google_api_key=GOOGLE_API_KEY
)

response = llm.invoke(
    "Explain what an AI agent is in one simple sentence."
)

print(response.content)

from typing import TypedDict


class ResearchState(TypedDict):
    question: str
    research_plan: str
    research_results: list
    analysis: str
    fact_check: str
    final_report: str
    research_attempts: int

from langchain_core.prompts import ChatPromptTemplate

planner_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a research planning agent.

Your job is to break a user's research question into
5 specific research tasks.

Do NOT answer the question.
Only create a clear research plan.

Return exactly 5 numbered research tasks."""
    ),
    ("human", "{question}")
])

planner_chain = planner_prompt | llm

question = "What are the effects of artificial intelligence on education?"

response = planner_chain.invoke({
    "question": question
})

print(response.content)

from typing import TypedDict, List
from langgraph.graph import StateGraph, START, END


class ResearchState(TypedDict):
    question: str
    research_plan: str
    research_results: List[str]
    analysis: str
    fact_check: str
    final_report: str

def planner_node(state: ResearchState):
    response = planner_chain.invoke({
        "question": state["question"]
    })

    # Gemini may return content as a list of blocks
    if isinstance(response.content, list):
        text = "\n".join(
            block.get("text", "")
            for block in response.content
            if isinstance(block, dict) and block.get("text")
        )
    else:
        text = response.content

    return {
        "research_plan": text
    }

graph = StateGraph(ResearchState)

graph.add_node("planner", planner_node)

graph.add_edge(START, "planner")
graph.add_edge("planner", END)

research_graph = graph.compile()

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": ""
})

print(result["research_plan"])

from google.colab import userdata
from tavily import TavilyClient

TAVILY_API_KEY = userdata.get("TAVILY_API_KEY")

tavily_client = TavilyClient(api_key=TAVILY_API_KEY)

print("Tavily connected successfully!")

results = tavily_client.search(
    query="latest applications of artificial intelligence in education",
    max_results=3
)

for result in results["results"]:
    print("TITLE:", result["title"])
    print("URL:", result["url"])
    print("CONTENT:", result["content"][:500])
    print("-" * 80)

from langchain_core.tools import tool

@tool
def web_search(query: str) -> str:
    """Search the web for reliable information about a research topic."""

    results = tavily_client.search(
        query=query,
        max_results=3
    )

    output = []

    for result in results["results"]:
        output.append(
            f"TITLE: {result['title']}\n"
            f"URL: {result['url']}\n"
            f"CONTENT: {result['content']}\n"
        )

    return "\n---\n".join(output)

researcher_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a research agent.

You receive a research plan created by another agent.

Your job is to:
1. Identify the most important research topics from the plan.
2. Create useful web search queries.
3. Use the web search tool to find relevant information.
4. Focus on trustworthy and recent sources.
5. Return the findings with the source title, URL, and important information.

Do not write the final report.
Your job is only to gather research evidence."""
    ),
    (
        "human",
        """Research question:
{question}

Research plan:
{research_plan}"""
    )
])

def get_text(response):
    """Convert Gemini response into plain text."""

    content = response.content

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        parts = []

        for block in content:
            if isinstance(block, dict):
                text = block.get("text")
                if text:
                    parts.append(text)

        return "\n".join(parts)

    return str(content)


def researcher_node(state: ResearchState):

    question = state["question"]
    research_plan = state["research_plan"]

    # Count how many times we have researched
    attempts = state.get("research_attempts", 0)

    # Ask Gemini to create 3 search queries
    query_prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are a web research query generator.

Given a research question and research plan, create exactly
3 useful web search queries.

The queries should cover different aspects of the topic.

Return ONLY the 3 queries, one per line.
Do not number them.
Do not add explanations."""
        ),
        (
            "human",
            """Research question:
{question}

Research plan:
{research_plan}"""
        )
    ])

    query_chain = query_prompt | llm

    query_response = query_chain.invoke({
        "question": question,
        "research_plan": research_plan
    })

    queries_text = get_text(query_response)

    print("Generated search queries:")
    print(queries_text)

    # Convert response into individual queries
    queries = [
        q.strip()
        for q in queries_text.split("\n")
        if q.strip()
    ]

    queries = queries[:3]

    # Search using Tavily
    research_results = []

    for query in queries:

        print(f"\nSearching: {query}")

        results = tavily_client.search(
            query=query,
            max_results=3
        )

        formatted_results = []

        for result in results["results"]:

            formatted_results.append(
                f"TITLE: {result.get('title', '')}\n"
                f"URL: {result.get('url', '')}\n"
                f"CONTENT: {result.get('content', '')}"
            )

        research_results.append(
            f"SEARCH QUERY: {query}\n\n"
            + "\n\n---\n\n".join(formatted_results)
        )

    return {
        "research_results": research_results,
        "research_attempts": attempts + 1
    }

graph = StateGraph(ResearchState)

graph.add_node("planner", planner_node)
graph.add_node("researcher", researcher_node)
graph.add_node("analyst", analyst_node)
graph.add_node("fact_checker", fact_checker_node)
graph.add_node("writer", writer_node)

graph.add_edge(START, "planner")
graph.add_edge("planner", "researcher")
graph.add_edge("researcher", "analyst")
graph.add_edge("analyst", "fact_checker")

graph.add_conditional_edges(
    "fact_checker",
    check_fact_quality,
    {
        "researcher": "researcher",
        "writer": "writer"
    }
)

graph.add_edge("writer", END)

research_graph = graph.compile()

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": ""
})

analyst_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are an expert research analyst.

You will receive:
1. A research question
2. A research plan
3. Raw web research collected by another agent

Your job is to analyze the research and identify the most important
findings.

For each major finding:
- Explain the finding clearly.
- Compare information from different sources when possible.
- Mention important evidence.
- Identify disagreements or limitations between sources.
- Do not invent facts.
- Keep the analysis organized and concise.

Do NOT write the final report yet.
Your job is only to analyze the evidence."""
    ),
    (
        "human",
        """Research Question:
{question}

Research Plan:
{research_plan}

Raw Research:
{research_results}"""
    )
])

def analyst_node(state: ResearchState):

    question = state["question"]
    research_plan = state["research_plan"]
    research_results = state["research_results"]

    # Combine all research results into one text
    combined_research = "\n\n".join(
        research_results
    )

    prompt = analyst_prompt.invoke({
        "question": question,
        "research_plan": research_plan,
        "research_results": combined_research
    })

    response = llm.invoke(prompt)

    analysis = get_text(response)

    return {
        "analysis": analysis
    }

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": ""
})

print("========== ANALYSIS ==========\n")
print(result["analysis"])

fact_checker_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a careful fact-checking research agent.

You will receive:
1. The original research question
2. An analysis produced by another agent
3. The original web research and sources

Your job is to check whether the important claims in the analysis
are supported by the available evidence.

For each important claim:

- State the claim.
- Decide whether it is Supported, Partially Supported, or Not Supported.
- Give a short explanation.
- Mention the relevant source URL when available.
- Do not invent evidence.
- If the evidence is insufficient, clearly say so.

Be objective and critical."""
    ),
    (
        "human",
        """Research Question:
{question}

Analysis:
{analysis}

Original Research:
{research_results}"""
    )
])

def fact_checker_node(state: ResearchState):

    question = state["question"]
    analysis = state["analysis"]
    research_results = state["research_results"]

    combined_research = "\n\n".join(research_results)

    prompt = fact_checker_prompt.invoke({
        "question": question,
        "analysis": analysis,
        "research_results": combined_research
    })

    response = llm.invoke(prompt)

    fact_check = get_text(response)

    return {
        "fact_check": fact_check
    }

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": ""
})

print("========== FACT CHECK ==========\n")
print(result["fact_check"])

writer_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are an expert academic research report writer.

Write a clear, well-structured research report using the research
evidence, analysis, and fact-checking results provided.

The report must contain:

1. Title
2. Introduction
3. Key Findings
4. Detailed Analysis
5. Ethical and Social Considerations
6. Limitations
7. Conclusion
8. Sources

Important rules:
- Use only information supported by the provided research.
- Do not invent statistics, studies, or sources.
- Clearly distinguish evidence from interpretation.
- Use a professional academic tone.
- Keep the report readable and well organized.
- Include source URLs where appropriate.
- Do not mention that you are an AI agent.
"""
    ),
    (
        "human",
        """Research Question:
{question}

Research Plan:
{research_plan}

Research Evidence:
{research_results}

Analysis:
{analysis}

Fact Check:
{fact_check}

Write the final research report."""
    )
])

def writer_node(state: ResearchState):

    question = state["question"]
    research_plan = state["research_plan"]
    research_results = state["research_results"]
    analysis = state["analysis"]
    fact_check = state["fact_check"]

    combined_research = "\n\n".join(research_results)

    prompt = writer_prompt.invoke({
        "question": question,
        "research_plan": research_plan,
        "research_results": combined_research,
        "analysis": analysis,
        "fact_check": fact_check
    })

    response = llm.invoke(prompt)

    final_report = get_text(response)

    return {
        "final_report": final_report
    }

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": ""
})

print(result["final_report"])

def check_fact_quality(state: ResearchState):

    fact_check = state["fact_check"].lower()

    if "not supported" in fact_check or "partially supported" in fact_check:
        return "researcher"

    return "writer"

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": ""
})

print(result["final_report"])

graph = StateGraph(ResearchState)

graph.add_node("planner", planner_node)
graph.add_node("researcher", researcher_node)
graph.add_node("analyst", analyst_node)
graph.add_node("fact_checker", fact_checker_node)
graph.add_node("writer", writer_node)

graph.add_edge(START, "planner")
graph.add_edge("planner", "researcher")
graph.add_edge("researcher", "analyst")
graph.add_edge("analyst", "fact_checker")

graph.add_conditional_edges(
    "fact_checker",
    check_fact_quality,
    {
        "researcher": "researcher",
        "writer": "writer"
    }
)

graph.add_edge("writer", END)

research_graph = graph.compile()

print("Graph compiled successfully!")

result = research_graph.invoke({
    "question": "What are the effects of artificial intelligence on education?",
    "research_plan": "",
    "research_results": [],
    "analysis": "",
    "fact_check": "",
    "final_report": "",
    "research_attempts": 0
})

print("Research completed!")

print(result["final_report"])
